-- +goose Up
CREATE TABLE account (
    id SERIAL PRIMARY KEY,
    document_number VARCHAR(255) NOT NULL UNIQUE,    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE account;