database:
  account:
    host: localhost
    user: postgres
    password: postgres
    dbname: account
    port: 5432
    sslmode: disable
    timezone: Asia/Shanghai
  transaction:
    dbname: transaction
    uri: mongodb://localhost:27017